version: 2.1


orbs:
  orb: invocations/orb@1.3.1


jobs:
  # Unit+integration tests, with coverage
  coverage:
    executor:
      name: orb/default
    steps:
      - orb/setup
      # Integration suite requires sudo, ssh
      - run: inv ci.make-sudouser
      - run: inv ci.make-sshable
      - run: sudo apt update
      - run: sudo apt install -y openssh-server wamerican-large
      - run: sudo /etc/init.d/ssh start
      - orb/sudo-coverage
      - orb/debug

  doctests:
    executor:
      name: orb/default
    steps:
      - orb/setup
      - run: inv www.doctest docs.doctest
      - orb/debug


  # TODO: when we feel safe nuking this, also fix up fabric/__init__.py to make
  # the 'auth' module import non-conditional (and update setup.py to require
  # paramiko>=3.2)
  v1_to_v2_shim:
    executor:
      name: orb/default
    steps:
      - orb/setup
      # nuke our default -e install of self, which will be non-2-suffixed
      - run: pip uninstall -y fabric
      # NOTE: no -e, just to be safe
      - run: "PACKAGE_AS_FABRIC2=y pip install ."
      # Safety check: we installed as fabric2
      - run: "pip list | grep -i fabric2"
      # Nab latest fabric1 from pypi
      - run: "pip install fabric\\<2"
      # Environment setup
      - run: "mkdir -p ~/.ssh && touch ~/.ssh/config"
      # Run the v1 shim test task
      - run: "inv safety-test-v1-to-v2-shim"


workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - coverage:
          name: Test
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          requires: ["Test"]
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      - orb/docs:
          name: "Docs"
          requires: ["Test"]
      - doctests:
          name: Doctests
          requires: ["Docs"]
      - v1_to_v2_shim:
          name: "v1-to-v2 shim test"
          requires: ["Test"]
