dist: xenial

language: python

branches:
  only:
  - master

services:
  - docker

python:
  # - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

before_install:
  - scripts/install-snappy.sh
  - scripts/install-leveldb.sh

install:
  - pip install -r requirements-dev.txt
  - make cython
  - pip install .

script:
  - make test
