# Config file for automatic testing at travis-ci.org

arch:
  - amd64
  - ppc64le
language: python

python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - pypy
  - pypy3
jobs:
 exclude:
  - arch: ppc64le
    python: pypy
  - arch: ppc64le
    python: pypy3

# command to install dependencies: 
install: pip install mock

# command to run tests: 
script: python setup.py test

