sudo: false
dist: trusty
language: bash

env:
  global:
    - CONDA=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - CONDA_ENV=environment.yml

before_install:
  - curl $CONDA > conda.sh
  - bash conda.sh -b -p $HOME/conda
  - export PATH=$HOME/conda/bin:$PATH
  - conda env update -n base -f $CONDA_ENV

install:
  - pip install .
  - mkdocs build
  - mv .gitignore .gitignore.bak # prepare gh-pages upload

script: 
  - python test.py

deploy:
  provider: pages
  local_dir: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  on:
    branch: master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/158c84e40cffffb115d3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always